version: "2"         # required to adjust maintainability checks
# checks:
exclude_patterns:
  # Master
  - "_includes/master"
  - "_websrc/gulp_tasks"
  - "_websrc/unit_tests"
  - "_site"
  # App
  - "module"
