name: Compile and Build Site

on:
  push:
    branches:
      - master
      - template

jobs:
  build:
    # needs: nothing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Run node install
        run: npm install
      - name: Run node build
        run: npm run build -- --buildLocation='server' --skipJekyll='true'
      - name: Push to gh-pages branch
        run: |
          export TZ=UTC date
          timestamp_utc=$(date +%FT%TZ)
          echo $timestamp_utc
          export TZ=America/Los_Angeles date
          timestamp_pst=$(date +%FT%TZ)
          echo $timestamp_pst

          github_repo=$(basename `git rev-parse --show-toplevel`)
          echo $github_repo

          github_origin_url=$(git remote get-url origin)
          echo $github_origin_url

          github_username="$(cut -d'/' -f4 <<<$github_origin_url)"
          echo $github_username

          build_log_path="@output/templated/build.json"
          sed "s/%TIMESTAMP_UTC_GHP%/$timestamp_utc/g" $build_log_path > "$build_log_path"-temp && mv "$build_log_path"-temp $build_log_path
          sed "s/%TIMESTAMP_PST_GHP%/$timestamp_pst/g" $build_log_path > "$build_log_path"-temp && mv "$build_log_path"-temp $build_log_path

          sed -n '1h;1!H;${;g;s/GEN>>>.*<<<GEN/<REDACTED FOR LIVE PUBLISH>/g;p;}' .gitignore > .gitignore

          git config user.email "email@email.com"
          git config user.name "Name"
          git add .
          git commit -m "Compile and Build: $timestamp_pst"
          git remote set-url origin https://iwiedenm:${{secrets.ACCESS_TOKEN}}@github.com/$github_username/$github_repo.git
          git remote -v
          git checkout -b gh-pages
          git push origin HEAD:gh-pages --force
      - name: Purge CloudFlare Cache
        run: |
          cf_zone=$(cat @output/.temp/cloudflare-zone.txt)
          curl -X POST https://api.itwcreativeworks.com/cloudflare -H "Content-Type: application/json" -d '{ "body": { "purge_everything": true }, "zone": "'$cf_zone'", "command": "purge_cache" }'
